# -*- coding: utf-8 -*-
"""Laboratorio Mapas en Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XFf08PzSMqgeAidXCU3w0sk3AQaxH76X
"""

import folium

from folium.plugins import minimap

ParqueJuanCastroBlanco = folium.Map(location=(10.2629827, -84.2805517))

ParqueJuanCastroBlanco

import folium
from folium.plugins import minimap
BenjaminNuñez = folium.Map(location=(9.9697604, -84.1316207))
BenjaminNuñez

from folium.plugins import MiniMap
from branca.element import Figure

popuptext = '<b>Heredia</b>'

my_map = folium.Map(location=[10.2856822, -84.9008912], zoom_start=16, tiles='stamenterrain')

folium.Marker(location=[10.2856822, -84.9008912], popup=popuptext, icon=folium.Icon(color="orange", icon="ok-sign")).add_to(my_map)

folium.Circle(location=[10.2856822, -84.9008912], color="purple", weight=6, fill_color="red", fill_opacity=0.5,
              tooltip="Heredia").add_to(my_map)

minimap = MiniMap(tile_layer='stamenterrain', position = 'bottomright')

my_map.add_child(minimap)

my_map.save('C:folium.html')

my_map

from folium.plugins import MiniMap
from branca.element import Figure

popuptext = '<b>Heredia</b>'

my_map = folium.Map(location=[9.9697604, -84.1316207], zoom_start=16, tiles='stamenterrain')

folium.Marker(location=[9.9697604, -84.1316207], popup=popuptext, icon=folium.Icon(color="orange", icon="ok-sign")).add_to(my_map)

folium.Circle(location=[9.9697604, -84.1316207], color="purple", weight=6, fill_color="red", fill_opacity=0.5,
              tooltip="Heredia").add_to(my_map)

minimap = MiniMap(tile_layer='stamenterrain', position = 'bottomright')

my_map.add_child(minimap)

my_map.save('C:folium.html')

my_map

fig = Figure(width=1000, height=500)
fig.add_child(my_map)
fig

